import sharp from 'sharp';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outDir = path.resolve(__dirname, '../public/images');

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

async function renderSvgToImage(svgStr, filename, width, height, format = 'jpeg') {
  const filePath = path.join(outDir, filename);
  // Don't overwrite if it was already generated by AI unless specified
  if (fs.existsSync(filePath)) {
    const stat = fs.statSync(filePath);
    if (stat.size > 20000 && !filename.startsWith('cert') && !filename.startsWith('404')) {
      console.log(`Skipping already generated: ${filename} (${stat.size} bytes)`);
      return;
    }
  }

  const buffer = Buffer.from(svgStr);
  let pipeline = sharp(buffer).resize(width, height);
  if (format === 'png') {
    await pipeline.png({ quality: 95 }).toFile(filePath);
  } else {
    await pipeline.jpeg({ quality: 92 }).toFile(filePath);
  }
  console.log(`Generated: ${filename} [${width}x${height}]`);
}

// 1. SERVICES
const services = [
  {
    name: 'service-facetas.jpg',
    title: 'Facetas de Porcelana',
    subtitle: 'Estética Dental de Alta Precisão',
    accent: '#0EA5A4',
    bg1: '#0F172A',
    bg2: '#134E4A',
    icon: `<path d="M400,180 C360,220 340,320 340,380 C340,430 370,460 400,460 C430,460 460,430 460,380 C460,320 440,220 400,180 Z" fill="#F8FAFC" stroke="#0EA5A4" stroke-width="8"/>
           <path d="M400,200 L400,440 M360,280 C380,310 420,310 440,280" stroke="#38BDF8" stroke-width="4" fill="none" opacity="0.6"/>
           <circle cx="400" cy="240" r="16" fill="#FBBF24" opacity="0.8"/>`
  },
  {
    name: 'service-lentes.jpg',
    title: 'Lentes de Contato Dental',
    subtitle: 'Lâminas Ultrafinas para o Sorriso Perfeito',
    accent: '#38BDF8',
    bg1: '#0F172A',
    bg2: '#0C4A6E',
    icon: `<path d="M350,220 C320,250 300,320 300,360 C300,400 320,430 350,430 C380,430 400,400 400,360 C400,320 380,250 350,220 Z" fill="#E0F2FE" opacity="0.8" stroke="#38BDF8" stroke-width="6"/>
           <path d="M430,190 L380,300 M430,190 L460,200" stroke="#FBBF24" stroke-width="6" stroke-linecap="round"/>
           <circle cx="430" cy="190" r="8" fill="#FBBF24"/>`
  },
  {
    name: 'service-odontopediatria.jpg',
    title: 'Odontopediatria',
    subtitle: 'Atendimento Lúdico e Especializado para Crianças',
    accent: '#F59E0B',
    bg1: '#1E1B4B',
    bg2: '#312E81',
    icon: `<circle cx="400" cy="270" r="90" fill="#FEF3C7" stroke="#F59E0B" stroke-width="8"/>
           <circle cx="370" cy="250" r="12" fill="#1E293B"/>
           <circle cx="430" cy="250" r="12" fill="#1E293B"/>
           <path d="M360,290 Q400,340 440,290" stroke="#EF4444" stroke-width="6" fill="#FFFFFF" stroke-linecap="round"/>
           <polygon points="400,140 415,175 450,175 422,195 433,230 400,210 367,230 378,195 350,175 385,175" fill="#FBBF24"/>`
  },
  {
    name: 'service-endodontia.jpg',
    title: 'Endodontia',
    subtitle: 'Tratamento de Canal com Tecnologia Rotatória',
    accent: '#06B6D4',
    bg1: '#0F172A',
    bg2: '#164E63',
    icon: `<path d="M400,160 C340,160 300,200 300,270 C300,330 330,400 360,480 C380,480 390,400 400,380 C410,400 420,480 440,480 C470,400 500,330 500,270 C500,200 460,160 400,160 Z" fill="#0F172A" stroke="#06B6D4" stroke-width="6"/>
           <path d="M370,270 C370,350 360,440 370,460 M430,270 C430,350 440,440 430,460" stroke="#EF4444" stroke-width="6" stroke-linecap="round"/>
           <circle cx="400" cy="230" r="15" fill="#38BDF8"/>`
  },
  {
    name: 'service-periodontia.jpg',
    title: 'Periodontia',
    subtitle: 'Saúde das Gengivas e Tecidos de Suporte',
    accent: '#10B981',
    bg1: '#064E3B',
    bg2: '#022C22',
    icon: `<path d="M280,320 Q400,380 520,320 L520,440 L280,440 Z" fill="#F43F5E" opacity="0.85"/>
           <path d="M330,330 C330,250 350,210 370,210 C390,210 400,250 400,330" fill="#FFFFFF" stroke="#E2E8F0" stroke-width="4"/>
           <path d="M400,330 C400,250 410,210 430,210 C450,210 470,250 470,330" fill="#FFFFFF" stroke="#E2E8F0" stroke-width="4"/>
           <line x1="470" y1="200" x2="410" y2="340" stroke="#10B981" stroke-width="6" stroke-linecap="round"/>`
  },
  {
    name: 'service-proteses.jpg',
    title: 'Próteses Dentárias',
    subtitle: 'Reabilitação Oral Fixa e Removível',
    accent: '#8B5CF6',
    bg1: '#2E1065',
    bg2: '#1E1B4B',
    icon: `<path d="M300,260 C300,200 500,200 500,260 C500,360 450,420 400,420 C350,420 300,360 300,260 Z" fill="none" stroke="#8B5CF6" stroke-width="8"/>
           <rect x="330" y="240" width="30" height="50" rx="8" fill="#FFFFFF" stroke="#CBD5E1" stroke-width="3"/>
           <rect x="370" y="235" width="30" height="55" rx="8" fill="#FFFFFF" stroke="#CBD5E1" stroke-width="3"/>
           <rect x="410" y="235" width="30" height="55" rx="8" fill="#FFFFFF" stroke="#CBD5E1" stroke-width="3"/>
           <rect x="450" y="240" width="30" height="50" rx="8" fill="#FFFFFF" stroke="#CBD5E1" stroke-width="3"/>`
  },
  {
    name: 'service-cirurgia.jpg',
    title: 'Cirurgia Oral',
    subtitle: 'Extrações Seguras e Pequenas Cirurgias',
    accent: '#3B82F6',
    bg1: '#0F172A',
    bg2: '#1E3A8A',
    icon: `<circle cx="400" cy="270" r="100" fill="#1E293B" stroke="#3B82F6" stroke-width="8"/>
           <line x1="340" y1="270" x2="460" y2="270" stroke="#60A5FA" stroke-width="12" stroke-linecap="round"/>
           <line x1="400" y1="210" x2="400" y2="330" stroke="#60A5FA" stroke-width="12" stroke-linecap="round"/>
           <circle cx="400" cy="270" r="18" fill="#FFFFFF"/>`
  },
  {
    name: 'service-bruxismo.jpg',
    title: 'Bruxismo e ATM',
    subtitle: 'Placas Miorrelaxantes e Alívio da Dor Orofacial',
    accent: '#EC4899',
    bg1: '#1F2937',
    bg2: '#374151',
    icon: `<path d="M310,230 C310,180 490,180 490,230 C490,320 440,360 400,360 C360,360 310,320 310,230 Z" fill="#FDF2F8" opacity="0.5" stroke="#EC4899" stroke-width="10"/>
           <path d="M330,240 C340,300 460,300 470,240" stroke="#F43F5E" stroke-width="6" stroke-linecap="round" fill="none"/>
           <circle cx="400" cy="270" r="14" fill="#FBBF24"/>`
  },
  {
    name: 'service-harmonizacao.jpg',
    title: 'Harmonização Orofacial',
    subtitle: 'Estética Funcional e Rejuvenescimento Natural',
    accent: '#D97706',
    bg1: '#1C1917',
    bg2: '#451A03',
    icon: `<path d="M330,220 C330,340 400,420 400,420 C400,420 470,340 470,220 C470,180 400,160 400,160 C400,160 330,180 330,220 Z" fill="none" stroke="#F59E0B" stroke-width="6"/>
           <circle cx="365" cy="260" r="6" fill="#FDE68A"/>
           <circle cx="435" cy="260" r="6" fill="#FDE68A"/>
           <path d="M375,320 Q400,340 425,320" stroke="#FDE68A" stroke-width="4" stroke-linecap="round" fill="none"/>
           <line x1="470" y1="200" x2="430" y2="240" stroke="#FBBF24" stroke-width="5" stroke-linecap="round"/>`
  }
];

// 2. DENTISTS
const dentists = [
  {
    filename: 'dentist-01.jpg',
    name: 'Dra. Ana Carolina Silva',
    cro: 'CRO-SP 89421',
    role: 'Ortodontista &amp; Alinhadores Invisíveis',
    bgGradient: ['#042F2E', '#0F766E'],
    accent: '#2DD4BF',
    gender: 'female',
    hairColor: '#451A03',
    skinColor: '#FBD38D'
  },
  {
    filename: 'dentist-02.jpg',
    name: 'Dr. Rafael Mendes',
    cro: 'CRO-SP 74102',
    role: 'Implantodontia &amp; Reabilitação Oral',
    bgGradient: ['#1E1B4B', '#312E81'],
    accent: '#818CF8',
    gender: 'male',
    glasses: true,
    hairColor: '#171717',
    skinColor: '#8C533C'
  },
  {
    filename: 'dentist-03.jpg',
    name: 'Dra. Juliana Tanaka',
    cro: 'CRO-SP 96320',
    role: 'Odontopediatria &amp; Prevenção Infantil',
    bgGradient: ['#1E293B', '#0369A1'],
    accent: '#38BDF8',
    gender: 'female',
    hairColor: '#18181B',
    skinColor: '#FED7AA'
  },
  {
    filename: 'dentist-04.jpg',
    name: 'Dr. Bruno Oliveira',
    cro: 'CRO-SP 81534',
    role: 'Endodontia Microscópica &amp; Canal',
    bgGradient: ['#18181B', '#3F3F46'],
    accent: '#FBBF24',
    gender: 'male',
    hairColor: '#27272A',
    skinColor: '#C68642'
  },
  {
    filename: 'dentist-05.jpg',
    name: 'Dra. Fernanda Costa',
    cro: 'CRO-SP 65219',
    role: 'Periodontia &amp; Plástica Gengival',
    bgGradient: ['#064E3B', '#047857'],
    accent: '#34D399',
    gender: 'female',
    hairColor: '#D97706',
    skinColor: '#FDE047'
  },
  {
    filename: 'dentist-06.jpg',
    name: 'Dr. Lucas Almeida',
    cro: 'CRO-SP 93245',
    role: 'Estética Dental, Lentes &amp; Harmonização',
    bgGradient: ['#1E3A8A', '#1D4ED8'],
    accent: '#60A5FA',
    gender: 'male',
    beard: true,
    hairColor: '#3B2F2F',
    skinColor: '#FDE68A'
  }
];

// 3. PATIENTS
const patients = [
  {
    filename: 'patient-01.jpg',
    name: 'Camila Ferreira',
    treatment: 'Lentes de Contato Dental',
    bg1: '#042F2E',
    bg2: '#115E59',
    accent: '#2DD4BF',
    skin: '#C68642',
    hair: '#1C1917',
    gender: 'female'
  },
  {
    filename: 'patient-02.jpg',
    name: 'Rodrigo Santoro',
    treatment: 'Implante Dentário Unitário',
    bg1: '#1E293B',
    bg2: '#334155',
    accent: '#38BDF8',
    skin: '#FCD34D',
    hair: '#52525B',
    gender: 'male'
  },
  {
    filename: 'patient-03.jpg',
    name: 'Beatriz Lima',
    treatment: 'Ortodontia com Alinhador',
    bg1: '#431407',
    bg2: '#78350F',
    accent: '#F59E0B',
    skin: '#6B4226',
    hair: '#171717',
    gender: 'female'
  },
  {
    filename: 'patient-04.jpg',
    name: 'Sebastião Nogueira',
    treatment: 'Prótese Protocolo Cerâmica',
    bg1: '#134E4A',
    bg2: '#0D9488',
    accent: '#99F6E4',
    skin: '#B45309',
    hair: '#E2E8F0',
    gender: 'male'
  },
  {
    filename: 'patient-05.jpg',
    name: 'Juliana e Miguel',
    treatment: 'Odontopediatria e Família',
    bg1: '#701A75',
    bg2: '#86198F',
    accent: '#F472B6',
    skin: '#FDE047',
    hair: '#78350F',
    gender: 'female'
  },
  {
    filename: 'patient-06.jpg',
    name: 'Mariana Chen',
    treatment: 'Clareamento Dental a Laser',
    bg1: '#1E1B4B',
    bg2: '#3730A3',
    accent: '#818CF8',
    skin: '#FEF08A',
    hair: '#09090B',
    gender: 'female'
  }
];

// 4. BLOGS
const blogs = [
  {
    filename: 'blog-01.jpg',
    category: 'PREVENCAO',
    title: 'Higiene Bucal Impecavel: O Passo a Passo Definitivo',
    accent: '#0EA5A4',
    bg1: '#0F172A',
    bg2: '#134E4A',
    iconText: 'DICAS'
  },
  {
    filename: 'blog-02.jpg',
    category: 'NUTRICAO E DENTES',
    title: 'Alimentos que Fortalecem o Esmalte e Evitam Caries',
    accent: '#10B981',
    bg1: '#064E3B',
    bg2: '#022C22',
    iconText: 'SAUDE'
  },
  {
    filename: 'blog-03.jpg',
    category: 'ODONTOPEDIATRIA',
    title: 'A Primeira Consulta do Bebe: Quando e Como Preparar',
    accent: '#F59E0B',
    bg1: '#312E81',
    bg2: '#1E1B4B',
    iconText: 'KIDS'
  },
  {
    filename: 'blog-04.jpg',
    category: 'TECNOLOGIA',
    title: 'Escaneamento Intraoral 3D: O Fim dos Moldes Desconfortaveis',
    accent: '#06B6D4',
    bg1: '#0F172A',
    bg2: '#164E63',
    iconText: '3D TECH'
  },
  {
    filename: 'blog-05.jpg',
    category: 'ESTETICA DENTAL',
    title: 'Clareamento Dental: Mitos, Verdades e Cuidados Pos-Procedimento',
    accent: '#EC4899',
    bg1: '#1F2937',
    bg2: '#374151',
    iconText: 'ESTETICA'
  },
  {
    filename: 'blog-06.jpg',
    category: 'DICAS PRATICAS',
    title: 'Como Usar o Fio Dental Corretamente sem Machucar a Gengiva',
    accent: '#3B82F6',
    bg1: '#0C4A6E',
    bg2: '#0369A1',
    iconText: 'HIGIENE'
  }
];

async function generateAll() {
  console.log('Generating missing images with sharp and styled SVGs...');

  // Generate Services
  for (const s of services) {
    const svg = `
      <svg width="800" height="600" viewBox="0 0 800 600" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <linearGradient id="g_${s.name}" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stop-color="${s.bg1}" />
            <stop offset="100%" stop-color="${s.bg2}" />
          </linearGradient>
          <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
            <feDropShadow dx="0" dy="8" stdDeviation="16" flood-color="#000000" flood-opacity="0.4" />
          </filter>
        </defs>
        <rect width="800" height="600" fill="url(#g_${s.name})" />
        <circle cx="400" cy="300" r="240" fill="${s.accent}" opacity="0.08" />
        <circle cx="700" cy="100" r="180" fill="${s.accent}" opacity="0.12" />
        <g filter="url(#shadow)">
          ${s.icon}
        </g>
        <!-- Overlay Card -->
        <rect x="50" y="460" width="700" height="100" rx="16" fill="#0F172ACC" stroke="${s.accent}" stroke-width="2" />
        <text x="80" y="505" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="28" font-weight="700" fill="#FFFFFF">${s.title}</text>
        <text x="80" y="535" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="16" font-weight="500" fill="#94A3B8">${s.subtitle}</text>
        <circle cx="710" cy="510" r="14" fill="${s.accent}" />
        <path d="M706,510 L714,510 M711,507 L714,510 L711,513" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    `;
    await renderSvgToImage(svg, s.name, 800, 600);
  }

  // Generate Dentists
  for (const d of dentists) {
    const svg = `
      <svg width="600" height="600" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <linearGradient id="bg_${d.filename}" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stop-color="${d.bgGradient[0]}" />
            <stop offset="100%" stop-color="${d.bgGradient[1]}" />
          </linearGradient>
          <linearGradient id="skin" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stop-color="${d.skinColor}" />
            <stop offset="100%" stop-color="${d.skinColor}" stop-opacity="0.9" />
          </linearGradient>
        </defs>
        <rect width="600" height="600" fill="url(#bg_${d.filename})" />
        <!-- Clinical Bokeh Lights -->
        <circle cx="120" cy="120" r="70" fill="${d.accent}" opacity="0.15" />
        <circle cx="480" cy="160" r="100" fill="#FFFFFF" opacity="0.08" />

        <!-- Doctor Portrait Vector -->
        <g transform="translate(0, 40)">
          <!-- Shoulders & Doctor Coat -->
          <path d="M120,560 Q300,430 480,560 L480,600 L120,600 Z" fill="#F8FAFC" />
          <path d="M250,460 L300,560 L350,460 L300,420 Z" fill="#0EA5A4" opacity="0.3" />
          <!-- Stethoscope or Teal Collar -->
          <path d="M220,490 C220,550 250,570 300,570 C350,570 380,550 380,490" stroke="${d.accent}" stroke-width="8" fill="none" stroke-linecap="round" />
          <circle cx="300" cy="570" r="12" fill="${d.accent}" stroke="#FFFFFF" stroke-width="3" />
          <!-- Neck -->
          <rect x="260" y="360" width="80" height="90" rx="10" fill="url(#skin)" />
          <!-- Face Head -->
          <ellipse cx="300" cy="270" rx="100" ry="120" fill="url(#skin)" />
          <!-- Hair -->
          ${d.gender === 'female'
            ? `<path d="M180,260 C180,140 420,140 420,260 C420,340 390,380 390,380 C390,380 410,220 300,200 C190,220 210,380 210,380 C210,380 180,340 180,260 Z" fill="${d.hairColor}" />`
            : `<path d="M190,250 C190,150 410,150 410,250 C410,210 390,160 300,160 C210,160 190,210 190,250 Z" fill="${d.hairColor}" />
               ${d.beard ? `<path d="M240,310 C240,370 360,370 360,310 C360,340 330,370 300,370 C270,370 240,340 240,310 Z" fill="${d.hairColor}" />` : ''}`}
          <!-- Glasses -->
          ${d.glasses ? `
            <rect x="230" y="240" width="55" height="40" rx="8" fill="none" stroke="#1E293B" stroke-width="5" />
            <rect x="315" y="240" width="55" height="40" rx="8" fill="none" stroke="#1E293B" stroke-width="5" />
            <line x1="285" y1="260" x2="315" y2="260" stroke="#1E293B" stroke-width="5" />
          ` : ''}
          <!-- Eyes & Eyebrows -->
          <circle cx="255" cy="255" r="7" fill="#1E293B" />
          <circle cx="345" cy="255" r="7" fill="#1E293B" />
          <!-- Smile -->
          <path d="M260,315 Q300,345 340,315" stroke="#E11D48" stroke-width="4" fill="#FFFFFF" stroke-linecap="round" />
        </g>
        <!-- Badge Info Bar -->
        <rect x="30" y="470" width="540" height="100" rx="16" fill="#0F172AF0" stroke="${d.accent}" stroke-width="2" />
        <text x="50" y="510" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="22" font-weight="700" fill="#FFFFFF">${d.name}</text>
        <text x="50" y="534" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="14" font-weight="600" fill="${d.accent}">${d.role}</text>
        <text x="50" y="555" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="12" font-weight="500" fill="#94A3B8">${d.cro} · Especialista Clínico</text>
      </svg>
    `;
    await renderSvgToImage(svg, d.filename, 600, 600);
  }

  // Generate Patients
  for (const p of patients) {
    const svg = `
      <svg width="400" height="400" viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <linearGradient id="pbg_${p.filename}" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stop-color="${p.bg1}" />
            <stop offset="100%" stop-color="${p.bg2}" />
          </linearGradient>
        </defs>
        <rect width="400" height="400" fill="url(#pbg_${p.filename})" />
        <circle cx="320" cy="80" r="60" fill="${p.accent}" opacity="0.2" />
        <g transform="translate(0, 30)">
          <!-- Patient Body -->
          <path d="M80,370 Q200,280 320,370 L320,400 L80,400 Z" fill="#F8FAFC" />
          <!-- Head -->
          <ellipse cx="200" cy="190" rx="70" ry="85" fill="${p.skin}" />
          <!-- Hair -->
          ${p.gender === 'female'
            ? `<path d="M120,180 C120,90 280,90 280,180 C280,240 260,270 260,270 C260,270 270,140 200,130 C130,140 140,270 140,270 C140,270 120,240 120,180 Z" fill="${p.hair}" />`
            : `<path d="M125,180 C125,100 275,100 275,180 C275,150 260,115 200,115 C140,115 125,150 125,180 Z" fill="${p.hair}" />`}
          <!-- Eyes -->
          <circle cx="175" cy="180" r="5" fill="#1E293B" />
          <circle cx="225" cy="180" r="5" fill="#1E293B" />
          <!-- Big natural white smile -->
          <path d="M170,225 Q200,255 230,225 Z" fill="#FFFFFF" stroke="#E11D48" stroke-width="2" />
        </g>
        <!-- Overlay pill -->
        <rect x="20" y="320" width="360" height="60" rx="14" fill="#0F172AE6" stroke="${p.accent}" stroke-width="1.5" />
        <text x="35" y="346" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="16" font-weight="700" fill="#FFFFFF">${p.name}</text>
        <text x="35" y="366" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="12" font-weight="600" fill="${p.accent}">Tratamento: ${p.treatment}</text>
      </svg>
    `;
    await renderSvgToImage(svg, p.filename, 400, 400);
  }

  // Generate Blog Thumbnails
  for (const b of blogs) {
    const svg = `
      <svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <linearGradient id="bbg_${b.filename}" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stop-color="${b.bg1}" />
            <stop offset="100%" stop-color="${b.bg2}" />
          </linearGradient>
        </defs>
        <rect width="1200" height="630" fill="url(#bbg_${b.filename})" />
        <circle cx="1000" cy="150" r="300" fill="${b.accent}" opacity="0.1" />
        <circle cx="200" cy="500" r="220" fill="#38BDF8" opacity="0.08" />

        <!-- Floating graphics / emoticons / icons -->
        <g transform="translate(750, 160)">
          <rect width="320" height="320" rx="36" fill="#0F172A99" stroke="${b.accent}" stroke-width="3" />
          <text x="160" y="180" font-family="system-ui, sans-serif" font-size="64" text-anchor="middle">${b.iconText}</text>
        </g>

        <!-- Post Content Header -->
        <rect x="80" y="100" width="220" height="42" rx="21" fill="${b.accent}" />
        <text x="190" y="127" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="16" font-weight="800" fill="#0F172A" text-anchor="middle" letter-spacing="0.1em">${b.category}</text>
        
        <foreignObject x="80" y="170" width="620" height="280">
          <div xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Plus Jakarta Sans', system-ui, sans-serif; font-size: 42px; font-weight: 800; color: #FFFFFF; line-height: 1.25;">
            ${b.title}
          </div>
        </foreignObject>

        <rect x="80" y="470" width="560" height="60" rx="14" fill="#FFFFFF12" />
        <text x="110" y="507" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="18" font-weight="600" fill="#E2E8F0">Artigo revisado por especialistas · Leitura de 4 min</text>
      </svg>
    `;
    await renderSvgToImage(svg, b.filename, 1200, 630);
  }

  // 37. 404 illustration
  const svg404 = `
    <svg width="800" height="800" viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="tgrad" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#F0FDFA" />
          <stop offset="100%" stop-color="#CCFBF1" />
        </linearGradient>
      </defs>
      <!-- Tooth Body -->
      <path d="M400,120 C280,120 200,200 200,340 C200,440 240,540 280,680 C320,680 340,560 360,500 C380,560 400,680 440,680 C480,540 520,440 520,340 C520,200 440,120 400,120 Z" fill="url(#tgrad)" stroke="#0EA5A4" stroke-width="16" />
      <!-- Sad Eyes -->
      <ellipse cx="330" cy="300" rx="16" ry="24" fill="#0F172A" />
      <ellipse cx="470" cy="300" rx="16" ry="24" fill="#0F172A" />
      <circle cx="336" cy="292" r="6" fill="#FFFFFF" />
      <circle cx="476" cy="292" r="6" fill="#FFFFFF" />
      <!-- Sad Eyebrows -->
      <path d="M300,250 Q330,270 360,250" stroke="#0F172A" stroke-width="8" stroke-linecap="round" fill="none" />
      <path d="M440,250 Q470,270 500,250" stroke="#0F172A" stroke-width="8" stroke-linecap="round" fill="none" />
      <!-- Sad Mouth -->
      <path d="M340,400 Q400,340 460,400" stroke="#0EA5A4" stroke-width="10" stroke-linecap="round" fill="none" />
      <!-- Tear -->
      <path d="M495,330 C495,350 480,365 480,365 C480,365 465,350 465,330 C465,315 480,305 480,305 C480,305 495,315 495,330 Z" fill="#38BDF8" />
      
      <!-- Placa 404 in hands -->
      <g transform="translate(240, 430)">
        <rect width="320" height="150" rx="24" fill="#FBBF24" stroke="#D97706" stroke-width="8" />
        <text x="160" y="105" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="82" font-weight="900" fill="#0F172A" text-anchor="middle">404</text>
      </g>
    </svg>
  `;
  await renderSvgToImage(svg404, '404-illustration.png', 800, 800, 'png');

  // 40. Open Graph Image
  const svgOg = `
    <svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="ogbg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#F0FDFA" />
          <stop offset="100%" stop-color="#CCFBF1" />
        </linearGradient>
      </defs>
      <rect width="1200" height="630" fill="url(#ogbg)" />
      <circle cx="1000" cy="200" r="300" fill="#0EA5A4" opacity="0.15" />
      
      <!-- Brand Logo in OG -->
      <g transform="translate(100, 100)">
        <rect width="80" height="80" rx="20" fill="#0EA5A4" />
        <path d="M40,15 C30,15 22,22 22,32 C22,40 25,46 27,56 C28,62 31,70 35,70 C39,70 39,60 40,57 C41,60 41,70 45,70 C49,70 52,62 53,56 C55,46 58,40 58,32 C58,22 50,15 40,15 Z" fill="#FFFFFF" />
        <text x="100" y="52" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="38" font-weight="800" fill="#0F172A">
          Sorriso<tspan fill="#0EA5A4">Perfeito</tspan>
        </text>
        <text x="102" y="76" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="16" font-weight="700" fill="#0D9488" letter-spacing="0.15em">
          CLÍNICA ODONTOLÓGICA DE ALTA PRECISÃO
        </text>
      </g>

      <!-- Headline -->
      <foreignObject x="100" y="240" width="650" height="240">
        <div xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Plus Jakarta Sans', system-ui, sans-serif; font-size: 52px; font-weight: 800; color: #0F172A; line-height: 1.15;">
          Cuidando do seu sorriso com tecnologia e carinho
        </div>
      </foreignObject>

      <!-- Features Pill -->
      <rect x="100" y="470" width="550" height="65" rx="32" fill="#FFFFFF" stroke="#0EA5A4" stroke-width="2" />
      <text x="130" y="510" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="20" font-weight="700" fill="#0F172A">
        ⭐ 4.9/5 · +2.000 Pacientes · Tecnologia 3D
      </text>

      <!-- Graphic Card Right -->
      <g transform="translate(800, 160)">
        <rect width="300" height="360" rx="28" fill="#1E3A8A" />
        <circle cx="150" cy="150" r="90" fill="#0EA5A4" opacity="0.4" />
        <path d="M150,90 C120,90 95,115 95,145 C95,175 105,190 115,225 C120,245 130,265 140,265 C150,265 150,235 150,230 C150,235 150,265 160,265 C170,265 180,245 185,225 C195,190 205,175 205,145 C205,115 180,90 150,90 Z" fill="#FFFFFF" />
        <text x="150" y="310" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="20" font-weight="700" fill="#FBBF24" text-anchor="middle">
          São Paulo - SP
        </text>
      </g>
    </svg>
  `;
  await renderSvgToImage(svgOg, 'og-image.jpg', 1200, 630);

  // 41. before-after-01.jpg (Clareamento)
  const svgBa1 = `
    <svg width="1000" height="600" viewBox="0 0 1000 600" xmlns="http://www.w3.org/2000/svg">
      <!-- Left side: ANTES -->
      <rect x="0" y="0" width="500" height="600" fill="#292524" />
      <g transform="translate(0, 50)">
        <text x="250" y="70" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="32" font-weight="800" fill="#F59E0B" text-anchor="middle">ANTES</text>
        <path d="M100,260 Q250,230 400,260 C400,380 340,440 250,440 C160,440 100,380 100,260 Z" fill="#E2D9B8" stroke="#78350F" stroke-width="8"/>
        <text x="250" y="370" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="20" font-weight="700" fill="#78350F" text-anchor="middle">Esmalte Amarelado / Manchas</text>
      </g>
      <!-- Split line -->
      <line x1="500" y1="0" x2="500" y2="600" stroke="#0EA5A4" stroke-width="8" />
      <!-- Right side: DEPOIS -->
      <rect x="500" y="0" width="500" height="600" fill="#042F2E" />
      <g transform="translate(500, 50)">
        <text x="250" y="70" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="32" font-weight="800" fill="#2DD4BF" text-anchor="middle">DEPOIS</text>
        <path d="M100,260 Q250,230 400,260 C400,380 340,440 250,440 C160,440 100,380 100,260 Z" fill="#FFFFFF" stroke="#0EA5A4" stroke-width="8"/>
        <text x="250" y="370" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="20" font-weight="700" fill="#0F766E" text-anchor="middle">Clareamento a Laser 8 Tons Mais Claro</text>
        <circle cx="340" cy="220" r="16" fill="#FBBF24" />
      </g>
      <rect x="350" y="520" width="300" height="50" rx="25" fill="#0EA5A4" />
      <text x="500" y="552" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="18" font-weight="800" fill="#FFFFFF" text-anchor="middle">CLAREAMENTO DENTAL</text>
    </svg>
  `;
  await renderSvgToImage(svgBa1, 'before-after-01.jpg', 1000, 600);

  // 42. before-after-02.jpg (Facetas)
  const svgBa2 = `
    <svg width="1000" height="600" viewBox="0 0 1000 600" xmlns="http://www.w3.org/2000/svg">
      <rect x="0" y="0" width="500" height="600" fill="#18181B" />
      <g transform="translate(0, 50)">
        <text x="250" y="70" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="32" font-weight="800" fill="#EF4444" text-anchor="middle">ANTES</text>
        <rect x="150" y="220" width="50" height="90" rx="10" fill="#E2E8F0" />
        <rect x="210" y="240" width="45" height="70" rx="8" fill="#CBD5E1" transform="rotate(-10 230 270)" />
        <rect x="270" y="210" width="50" height="100" rx="10" fill="#E2E8F0" />
        <text x="250" y="380" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="18" font-weight="700" fill="#A1A1AA" text-anchor="middle">Dentes Desiguais e Fraturados</text>
      </g>
      <line x1="500" y1="0" x2="500" y2="600" stroke="#38BDF8" stroke-width="8" />
      <rect x="500" y="0" width="500" height="600" fill="#0C4A6E" />
      <g transform="translate(500, 50)">
        <text x="250" y="70" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="32" font-weight="800" fill="#38BDF8" text-anchor="middle">DEPOIS</text>
        <rect x="130" y="210" width="55" height="100" rx="12" fill="#FFFFFF" stroke="#38BDF8" stroke-width="3" />
        <rect x="195" y="200" width="55" height="110" rx="12" fill="#FFFFFF" stroke="#38BDF8" stroke-width="3" />
        <rect x="260" y="200" width="55" height="110" rx="12" fill="#FFFFFF" stroke="#38BDF8" stroke-width="3" />
        <rect x="325" y="210" width="55" height="100" rx="12" fill="#FFFFFF" stroke="#38BDF8" stroke-width="3" />
        <text x="250" y="380" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="18" font-weight="700" fill="#BAE6FD" text-anchor="middle">Lentes &amp; Facetas de Porcelana Uniformes</text>
      </g>
      <rect x="350" y="520" width="300" height="50" rx="25" fill="#0284C7" />
      <text x="500" y="552" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="18" font-weight="800" fill="#FFFFFF" text-anchor="middle">FACETAS DE PORCELANA</text>
    </svg>
  `;
  await renderSvgToImage(svgBa2, 'before-after-02.jpg', 1000, 600);

  // 43. before-after-03.jpg (Ortodontia)
  const svgBa3 = `
    <svg width="1000" height="600" viewBox="0 0 1000 600" xmlns="http://www.w3.org/2000/svg">
      <rect x="0" y="0" width="500" height="600" fill="#1E1B4B" />
      <g transform="translate(0, 50)">
        <text x="250" y="70" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="32" font-weight="800" fill="#F43F5E" text-anchor="middle">ANTES</text>
        <path d="M120,240 C160,200 210,290 260,210 C310,280 370,190 400,240" stroke="#CBD5E1" stroke-width="26" stroke-linecap="round" fill="none"/>
        <text x="250" y="370" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="18" font-weight="700" fill="#A5B4FC" text-anchor="middle">Apinhamento e Desalinhamento Severo</text>
      </g>
      <line x1="500" y1="0" x2="500" y2="600" stroke="#8B5CF6" stroke-width="8" />
      <rect x="500" y="0" width="500" height="600" fill="#2E1065" />
      <g transform="translate(500, 50)">
        <text x="250" y="70" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="32" font-weight="800" fill="#C084FC" text-anchor="middle">DEPOIS</text>
        <path d="M120,250 C180,210 250,200 320,210 C360,220 400,250 400,250" stroke="#FFFFFF" stroke-width="26" stroke-linecap="round" fill="none"/>
        <text x="250" y="370" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="18" font-weight="700" fill="#E9D5FF" text-anchor="middle">Alinhamento Perfeito com Invisalign</text>
      </g>
      <rect x="350" y="520" width="300" height="50" rx="25" fill="#7C3AED" />
      <text x="500" y="552" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="18" font-weight="800" fill="#FFFFFF" text-anchor="middle">ORTODONTIA INVISÍVEL</text>
    </svg>
  `;
  await renderSvgToImage(svgBa3, 'before-after-03.jpg', 1000, 600);

  // 45. certification-01.png
  const svgCert1 = `
    <svg width="500" height="500" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
      <circle cx="250" cy="250" r="230" fill="#0EA5A4" />
      <circle cx="250" cy="250" r="210" fill="#FFFFFF" stroke="#0D9488" stroke-width="4" stroke-dasharray="8 6" />
      <circle cx="250" cy="250" r="170" fill="#F0FDFA" />
      
      <!-- Tooth Center -->
      <path d="M250,150 C230,150 215,165 215,185 C215,200 220,215 225,235 C230,250 235,270 242,270 C250,270 250,255 250,250 C250,255 250,270 258,270 C265,270 270,250 275,235 C280,215 285,200 285,185 C285,165 270,150 250,150 Z" fill="#0EA5A4" />
      <text x="250" y="310" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="26" font-weight="800" fill="#0F172A" text-anchor="middle">CLÍNICA CERTIFICADA</text>
      <text x="250" y="340" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="20" font-weight="700" fill="#0D9488" text-anchor="middle">CRO-SP 12345</text>
      <text x="250" y="370" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="14" font-weight="600" fill="#64748B" text-anchor="middle">PADRÃO OURO DE QUALIDADE</text>
    </svg>
  `;
  await renderSvgToImage(svgCert1, 'certification-01.png', 500, 500, 'png');

  // 46. certification-02.png
  const svgCert2 = `
    <svg width="500" height="500" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="shieldGrad" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#1E3A8A" />
          <stop offset="100%" stop-color="#1E40AF" />
        </linearGradient>
      </defs>
      <!-- Shield Badge -->
      <path d="M250,30 L430,90 C430,310 250,470 250,470 C250,470 70,310 70,90 Z" fill="url(#shieldGrad)" stroke="#38BDF8" stroke-width="10" />
      <!-- Inner Shield Line -->
      <path d="M250,60 L400,110 C400,290 250,420 250,420 C250,420 100,290 100,110 Z" fill="none" stroke="#60A5FA" stroke-width="3" stroke-dasharray="6 6" />
      
      <!-- Lock or Check Icon -->
      <path d="M190,220 L230,260 L320,160" stroke="#10B981" stroke-width="20" stroke-linecap="round" stroke-linejoin="round" fill="none" />
      
      <text x="250" y="330" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="34" font-weight="900" fill="#FFFFFF" text-anchor="middle">LGPD</text>
      <text x="250" y="365" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="20" font-weight="700" fill="#38BDF8" text-anchor="middle">COMPLIANT</text>
      <text x="250" y="395" font-family="'Plus Jakarta Sans', system-ui, sans-serif" font-size="14" font-weight="600" fill="#93C5FD" text-anchor="middle">DADOS SEGUROS &amp; PRIVACIDADE</text>
    </svg>
  `;
  await renderSvgToImage(svgCert2, 'certification-02.png', 500, 500, 'png');

  console.log('All image assets generated successfully!');
}

generateAll().catch(err => {
  console.error(err);
  process.exit(1);
});
